### ISSUE TITLE
Add a prototype implementation to discuss further

### ISSUE THREAD

**Issue by deeplook** [giswqs/leafmaptools#3]
This should implement an initial fabric of building blocks to illustrate how they might work together.

**Comment by deeplook** [comment]
An initial prototype can be found here: https://github.com/giswqs/leafmaptools/tree/master/prototypes. Will add a GIF shortly, too.

**Comment by deeplook** [comment]
GIF and one more tool added.

**Comment by giswqs** [comment]
@deeplook Sorry, I am a bit behind. Should this feature be merged into the main module?

**Comment by deeplook** [comment]
@giswqs I can put this into the right place and make it "usable", but I'm sure this will still change a lot. I want to explore some layout options with widgets off the map. If you want to do _something_ simple (simple because you've done so much of it already) I can think of adding some prototype for a menu with plugins for such widgets.
